# Generated by Django 5.2.8 on 2026-05-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
