# Generated by Django 5.2.8 on 2026-05-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelvendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
