# Generated by Django 5.2.8 on 2026-05-20 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_slug',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='accounts.hotel')),
            ],
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
